### ISSUE TITLE
iOS Build Error

### ISSUE THREAD

**Issue by kamaeleon** [sharmapranav/Xamarin#1]
Hi
I loaded your sample. It works with android but with iOS i have an build error.

Error		Unpacking failed. Please download 'https://dl.google.com/dl/cpdc/7d719f8d49d44418-Google-Mobile-Ads-SDK-7.15.0.tar.gz' and extract it to the 'C:\Users\...\AppData\Local\XamarinBuildDownloadCache\Gmbladssdk-7.15.0' directory and create an empty file called 'C:\Users\...\AppData\Local\XamarinBuildDownloadCache\Gmbladssdk-7.15.0.unpacked'.	Ads.iOS		

Is that a new bug in xamarin? I have read this issue also from a other user in other portal. Any idea to fix this?

**Comment by kamaeleon** [comment]
Hi 
I have fixed this issue. 
I don´t know what´s the problem is exacly. But I have self extracted the download file in two steps. I copied the unpacked file from a other unpacked file and renamed it. I followed the next error instruction in the build and then was it fixed.  

It works :)

**Comment by sharmapranav** [comment]
It looks like some Xamarin issue that only hapens on Windows. It builds with no issues on Mac for me.
