### ISSUE TITLE
Ad shows up on iOS but immediately disappears

### ISSUE THREAD

**Issue by vincentcastagna** [sharmapranav/Xamarin#10]
Hello,

First thank your for this sample. 
Everything's working fine on Android but on iOS when interstitial ad appears, it disappears immediately after being showed up (like 2sec). Can't figure out whats going on . Any idea ? 

Thanks.

**Comment by sharmapranav** [comment]
Not sure, can you maybe post the log output?

**Comment by vincentcastagna** [comment]
Hello,

Sorry was one of my nuget's package that was conflicting with the ad on iOS. I'm using the RGplugin popup for loader display, and when popping the page, it was popping the ad too. Thanks anyway for your answer and great example provided :).
