### ISSUE TITLE
ViewRenderer() is obsolete you need use ViewRenderer(Context) from 2.5 version

### ISSUE THREAD

**Issue by Rombersoft** [sharmapranav/Xamarin#7]

**Comment by thiago-rcarvalho** [comment]
Hello, 

You can bypass the warning simply adding a constructor to your AdBanner_Droid viewRenderer. Like the code below:

```
public AdBanner_Droid(Context context) : base(context)
 {
 }
```

**Comment by Rombersoft** [comment]
I've already fixed it

Ср, 2 трав. 2018 р., 00:35 користувач Thiago Carvalho <
notifications@github.com> пише:

**Comment by sharmapranav** [comment]
Feel free to create a pull request if you guys would like me to merge your fixes.
