### ISSUE TITLE
Warning: Attempt to present <GADInterstitialViewController: 0x13a8aa400> on <Xamarin_Forms_Platform_iOS_PlatformRenderer: 0x139e9fd10> whose view is not in the window hierarchy!

### ISSUE THREAD

**Issue by treidio** [sharmapranav/Xamarin#8]
Hi sharmapranav,

thanks for your code snippets. I had this error on using your interstitial code in forms. I don't know how to do a pull request, so rather than pretend I can.. here is the fix.

have a great click rate :)

https://github.com/sharmapranav/Xamarin/blob/master/Ads/Ads/Ads.iOS/AdInterstitial_iOS.cs

fix is

        public void ShowAd()
        {
            if (interstitial.IsReady)
            {
                interstitial.ScreenDismissed += (s, e) => LoadAd();
                var viewController = UIApplication.SharedApplication.KeyWindow.RootViewController;
                interstitial.PresentFromRootViewController(GetTopViewController());
            }
        }
        public static UIViewController GetTopViewController()
        {
            var window = UIApplication.SharedApplication.KeyWindow;
            var vc = window.RootViewController;
            while (vc.PresentedViewController != null)
                vc = vc.PresentedViewController;

            if (vc is UINavigationController navController)
                vc = navController.ViewControllers.Last();

            return vc;
        }

**Comment by sharmapranav** [comment]
Hey mate, thanks for providing the fix. Did you have the iOS issue with this sample project or within one of your own projects? Because I did not have any issues running the sample project.

**Comment by treidio** [comment]
my own project. i found it from other people having similar errors
elsewhere.  cut n paste..
i think this makes sure to get the right vc where for your project the vc
is convenient


cheers

**Comment by sharmapranav** [comment]
Thanks mate, I added your fix and merged it into the master branch for others.

Cheers
